apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clinic

resources:
  - namespace.yaml
  - common/clinic-config.yaml
  - common/postgres-init.yaml
  - postgres
  - identity-service
  - clinic-service
  - api-gateway
